// GENERATED by scripts/gen-selectors.mjs. DO NOT EDIT.
// Regenerate with: node scripts/gen-selectors.mjs
//
// Event keys and entry-point selectors for the NIGHTSHIFT vault and gate,
// computed with starknet.js hash.getSelectorFromName over the names in
// src/vault.cairo and src/gate.cairo.
//
// Event layout, as the Cairo declares it. keys[0] is always the selector of
// the variant name; every #[key] field follows in keys[1..]; everything else is
// positional in data[].
//
//   vault Subscribed        keys: commitment                data: creator_id, n_periods
//   vault CreatorRegistered keys: creator_id                data: token, tiers
//   vault Charged           keys: commitment                data: period_index, amount, by
//   vault Claimed           keys: creator_id                data: amount
//   vault ClaimedPublic     keys: creator_id                data: to, amount
//   vault Cancelled         keys: commitment                data: (empty)
//   vault Reclaimed         keys: commitment                data: amount
//   gate  Presented         keys: commitment, verifier_id   data: expiry_block, creator_id, tier
//
// Presented is the one event with TWO indexed fields, so its creator_id is in
// data[1] and cannot be filtered server-side. Filter it on the commitment set.

/** Vault event keys (keys[0] of a vault event). */
export const EVENT = {
  Subscribed: "0x001757823b1d7233f8d4a0e3b3766c8a572e33e572b950f099f5338858558d78",
  CreatorRegistered: "0x02e157d6a333860c608205c421cea4d424a2f8d4b90da8290adfa0b6c2d16f49",
  Charged: "0x0185ca81badbc5dd12754d07ca82c20ece8887f3e68ce333c631ac3e4faaaa6a",
  Claimed: "0x035cc0235f835cc84da50813dc84eb10a75e24a21d74d6d86278c0f037cb7429",
  ClaimedPublic: "0x02644f8285977fd93c9295d9b65bb47899f218695f9bcb51729d2ba2a6b175fc",
  Cancelled: "0x037a39c9fa82f68622f45ae205e399b0f0a7252140d9357a90220c542bb4ef4b",
  Reclaimed: "0x02621780bee6cc1a49e453a9b464936cf8ac63ce945508912c5f966df0cf29fa",
} as const;

/** Gate event keys. */
export const GATE_EVENT = {
  Presented: "0x03be77418b7093aa5e3ad88f5fa7234a978d159d6adeeb5bb8d4c808a2170e9b",
} as const;

/** The v2 vault called its charge event Released. Kept for the banked v2
 *  receipts the board still decodes. */
export const LEGACY_EVENT = {
  Released: "0x0127adceb04d96dd7337eb363a9dd96b0fe957ce88be4b770ba4ef9fdc970f7f",
} as const;

/** Vault entry-point selectors. */
export const VAULT_SELECTOR = {
  privacy_invoke: "0x00402925cce9218828b3ac9a72ac249103f8448a1e1d73c3efaf5da992625043",
  charge: "0x0041e29a5fa861d1ebc1d6a8c96a9f9831e2f7a8e28a2f8150515042a6a44db4",
  register_creator: "0x00e8fc97920f8289b7d9717d696c78d3c44eb8d65199a8a8ef71ec8d3a75df23",
  cancel: "0x02979287743fc9323bd8e3f513f06468849cf4695b9599f9e20e9704e0077523",
  reclaim: "0x029a74d0248690b4ebefd08f0a1d7ca1088c7cb0e9d9ce824f3bc42f3f74ec05",
  claim_public: "0x021fb5a632b81e34a9f4471f4f993936098461a8930846f09fdc828cfe999b6a",
  accounted: "0x019fcbfd1cca23ace0b1d37e31b7215f7c14f51f0aecda59ccbc8cbd93e4a98e",
  is_active: "0x028cd1b9b7a6254f5219ad13ceac17ed7e5c245c1b5f97c1a9c7f69d59cd819f",
  owner_key_of: "0x03eaaf08c67d4213c7086682b160899d88006ba5c2cc6c0f0aa419a0edcaeffa",
  claimable_of: "0x018b395b0d24129c0ff984dc86392c8e2ad46d22917022de918ed6a7d7e079e8",
  claim_pub_nonce_of: "0x0329ccf06bcfd631d41ed3d4dd72bd61b8cb336ec423e579a43511b82fdd138b",
  schedule_of: "0x0006144a86927693b64998a059d475df8f31c8e4e73d3afafd1b2fb8530f27b4",
  tier_of: "0x00824c6d16cb8b8f3f6bc9ce0867924246ad66c3ce4e738e97fc8e8c292f58fb",
  periods_due: "0x00937e29c08adedb46e8432756b95fbf4ddb3685a0eee04ac7bd31344aef8d34",
  period_charged: "0x029f68f806bb6523a76f4ced4da0904d71c15b283f1477bc82e4c1016ffce962",
} as const;

/** Gate entry-point selectors. `is_active` and `tier_of` collide by name with
 *  the vault's, since a selector hashes the name alone. Same selector, different
 *  contract address, different signature. */
export const GATE_SELECTOR = {
  present: "0x0166cb87b74c49cc102de8d1e9a99f209991638b2efd2723b40d76df1147971a",
  vault: "0x03c14fceac7676b670aa56866076586ea1ce15ddcf19208ec6346cf748dffbee",
  is_active: "0x028cd1b9b7a6254f5219ad13ceac17ed7e5c245c1b5f97c1a9c7f69d59cd819f",
  presentable: "0x006329a8a03fc415fc5bc9d152a07a08e7b31d7660053d332f5b47e0f01da096",
  tier_of: "0x00824c6d16cb8b8f3f6bc9ce0867924246ad66c3ce4e738e97fc8e8c292f58fb",
} as const;

/** Felt comparison that ignores leading-zero padding. RPC nodes are not
 *  consistent about padding event keys, so never compare these as strings. */
export const feltEq = (a: string, b: string): boolean => BigInt(a) === BigInt(b);

/** 0x + 64 hex, the padded form used throughout this file. */
export const feltPad = (a: string): string =>
  `0x${BigInt(a).toString(16).padStart(64, "0")}`;
